version: "3.8"

services:
  ml_api:
    build: .
    container_name: ml-api-container
    ports:
      - "8000:8000"
    environment:
      MODEL_PATH: "/app/models/my_classifier_model.keras"
    restart: always